import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanStackProvider from "./components/provider/tanstack";
import DashBoard from "./components/common/dashboard";
import { NextAppProvider } from '@toolpad/core/nextjs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en, fa">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanStackProvider>
          {children}
        </TanStackProvider>
      </body>
    </html>
  );
}
