import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanStackProvider from "./components/provider/tanstack";
import RTLThemeProvider from "./components/provider/theme";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RTLThemeProvider>
          <TanStackProvider>{children}</TanStackProvider>
        </RTLThemeProvider>
      </body>
    </html>
  );
}
